name: Release

on:
  release:
    types: [ published ]
{% raw %}
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false
{% endraw %}
          python-version: "{{ cookiecutter._python_version_specs[cookiecutter.python_version]['versions'][0] }}"
{% raw %}
      - name: Publish to pypi
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish --build
      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force{% endraw +%}
